### ISSUE TITLE
Is there a way to install an older version of Cassandra?

### ISSUE THREAD

**Issue by ruslan-ryzhkov** [michaelklishin/cassandra-chef-cookbook#183]
I'm looking to install Cassandra version 2.0.8 but when I run the cookbook using this version argument, I get a dependency error because dsc20 automatically uses the latest version which is 2.0.13-1. Is there a way to specify dsc20 to use 2.0.8-1 (or some other version compatible with Cassandra 2.0.8)?  I didn't see a version argument in /attributes/datastax.rb although the package_name attribute is there.  This is the command that is being run:

                          apt-get -q -y install dsc20=2.0.13-1

This is the error message:

                          The following packages have unmet dependencies:
                          dsc20 : Depends: cassandra (= 2.0.13) but 2.0.8 is to be installed

  I just want to change the version to 2.0.8-1 or some other version compatible with Cassandra version 2.0.8.

**Comment by sethrosenblum** [comment]
Are you using the latest version of the cookbook?  This should have been fixed in #169 .

**Comment by ruslan-ryzhkov** [comment]
I was using the tag option in my Berksfile and specified version 2.9.0. I changed the branch to master instead and re-ran the cookbook but got the same error.  However, the command that is being run is this one now:

apt-get -q -y --force-yes -o Dpkg::Options::="--force-confold" install dsc20=2.0.13-1

The error message is still the same.

**Comment by michaelklishin** [comment]
@ruslan-ryzhkov are you specifying the required node attributes? https://github.com/michaelklishin/cassandra-chef-cookbook/pull/169/files#diff-169a0a6503fec27af67a3a0f89210d23R88

**Comment by ruslan-ryzhkov** [comment]
I'm passing the attributes in Custom Chef JSON on AWS OpsWorks when I create a new stack like this:

{
  "cassandra":{
       "cluster_name":"Test",
       "version":"2.0.8"
    }
}

If I change version to be 2.0.13, my instance loads fine but 2.0.8 fails.

**Comment by michaelklishin** [comment]
I don't think we have the resources to support older point release such as 2.0.8 (instead of 2.0.13).
